apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil-playground-app
  name: wil-nodeport
spec:
  type: NodePort
  selector:
    app: wil-playground-app
  ports:
  - port: 8888
    nodePort: 30014
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground-deployment
  labels:
    app: wil-playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground-app
  template:
    metadata:
      labels:
        app: wil-playground-app
    spec:
      containers:
      - name: will-container
        image: wil42/playground:v2
        ports:
        - containerPort: 8888