apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
<<<<<<< HEAD
    # nginx.ingress.kubernetes.io/default-backend: default-backend
spec:
  defaultBackend:
    service:
      name: default-backend
      port:
        number: 80
=======
spec:
  defaultBackend:
      service:
        name: default-backend
        port:
          number: 80
>>>>>>> fea322a167eabee88ef38fac8dcef9a241e34759
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-one
            port:
              number: 80
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-two
            port:
              number: 80
  - host: app3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-three
            port:
              number: 80
  - http:
<<<<<<< HEAD
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
=======
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
>>>>>>> fea322a167eabee88ef38fac8dcef9a241e34759
              name: app-three
              port:
                number: 80